services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

    ports:
      - "9200:9200"

  movie-search-app:
    build: .

    depends_on:
      - elasticsearch

    ports:
      - "3000:3000"

    volumes:
      - ./data:/app/data

    environment:
      PORT: 3000

      ELASTICSEARCH_NODE: http://elasticsearch:9200

      AUTO_INGEST: true

      MOVIES_CSV_PATH: /app/data/tmdb_5000_movies.csv

      CREDITS_CSV_PATH: /app/data/tmdb_5000_credits.csv

      INGESTION_RETRIES: 5

      INGESTION_RETRY_DELAY_MS: 3000